# .github/workflows/test_action.yml
name: Test Action
on: [push]

jobs:
  trigger-deployment:
    runs-on: [self-hosted]
    name: Trigger Service deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trigger
        id: trigger
        uses: ./ # Uses an action in the root directory
        with:
          service-name: test-service
          service-version: v0.0.1
          deployment-repo: dummy
          github-token: dummy
      - name: Print outputs
        run: |
            echo "Status: ${{ steps.trigger.outputs.status }}"
            echo "MR: ${{ steps.trigger.outputs.merge_request_link }}"